### ISSUE TITLE
Seperate config from cronjob.sh

### ISSUE THREAD

**Issue by tarkah** [taylorbourne/xteve_lazystream#11]
We need to make the `cronjob.sh` something that the user can't directly edit, but they can supply variables for / edit an actual config file. Because if a change is needed to the cronjob.sh, it's currently up to the user to overwrite their file in `/config` with any changes. `/config` volume should have an actual config file they can maintain, which will be populated w/ defaults if it doesn't already exist, which can then be sourced from to run the `cronjob.sh`

**Comment by taylorbourne** [comment]
Fixed in #13
