### ISSUE TITLE
Get cronjob.sh output to display in container log along w/ xteve output

### ISSUE THREAD

**Issue by tarkah** [taylorbourne/xteve_lazystream#12]
Not sure at this point how to accomplish this, but it'd be nice to see the cronjob output in the container logs along with xteve output. I'll look into best practice way to do this.

**Comment by taylor-verys** [comment]
Noticed the same – for a moment it made me think that the cronjob wasn't running. I'll look into this as well.

**Comment by tarkah** [comment]
I have a PR landing soon that has a bunch of structural changes that I think you'll like, and it is able to capture the cron output

**Comment by taylorbourne** [comment]
Fixed in #13
