### ISSUE TITLE
Guide2Go Version 

### ISSUE THREAD

**Issue by MaDTaZ** [taylorbourne/xteve_lazystream#19]
Hey 
By the way this is great and love the work been a great find for the playoffs.  Once question I had was I noticed that guide2go is not the newest version.  Do you update that in the image for would that come directly from xteve?.  

Any help would be appreciated I started using it for all my feeds so really want to get guide2go working and the configure json is taking a long time but with the one that I installed on my buddy which is not in docker and newer it doesnt take as long.

Forgot to add which one is faster 1.1.2 is the one I dont have in the container.  Running 1.0.6 is the one in the container

Also found that I am getting this error how do I fix this
2020/08/19 08:18:49 [guide2go] Config file: /guide2go/
2020/08/19 08:18:49 [ERROR] - read /guide2go/: is a directory

**Comment by taylorbourne** [comment]
Hm not sure I've seen that before. Let me take a look at updating guide2go, hoping there are no breaking changes.

**Comment by taylorbourne** [comment]
@MaDTaZ looks like updating guide2go would require changes to our config files, as the github over there specifically says

> Configuration files from version 1.0.6 or earlier are not compatible!

I'll read through the changes and get my config updated so I'll be able to test this out. Hopefully I can get to this tonight.

**Comment by MaDTaZ** [comment]
Ya now that I look back in the command prompt I see that message as well should of included the whole thing.
When ever you get a chance I have just installed standalone for now and created a task to dump it to the folder.  

So no hurry here

**Comment by taylorbourne** [comment]
Looks like updating the config to `yaml` format is pretty easy so I don't see this being such a huge deal – opened up a PR to get this updated. Once I merge it up I'll release `1.1.0` 👍

**Comment by taylorbourne** [comment]
@MaDTaZ try the latest release, `1.1.1` – it's working great for me so far.
