### ISSUE TITLE
EPG Not loading in Plex

### ISSUE THREAD

**Issue by ovcrash** [taylorbourne/xteve_lazystream#21]
Hi,

Great docker, thanks.

The only little problem i have is that in Plex the EPG is not loading. If i go directly to the http site for the xml file, i can see the channels and the program. It doesn't show up in Plex, and i manually added the EPG information pointing to the url of the xml file.

Anything i'm missing ?

Thanks.

**Comment by taylorbourne** [comment]
I've seen this come through as a issue with xTeVe itself. I recommend adding a volume mapping to Plex so you can have it read the file directly rather than through the web server. Let me know if that helps!

**Comment by tarkah** [comment]
As @taylorbourne said, this is an xteve issue. See the solution here: https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#plex

**Comment by ovcrash** [comment]
Hi,

Thanks for the information, yes i confirm that with the xml file it works.
