### ISSUE TITLE
Issue with new install

### ISSUE THREAD

**Issue by MaDTaZ** [taylorbourne/xteve_lazystream#25]
So I decided to start fresh to make sure i did it right and this is the message I am getting when i run crontab
madtaz@OrignalDarkNet:~/Downloads/xteve_lazystream$ docker exec -it xteve_lazystream ./cronjob.sh
2020/08/20 16:15:08 [cronjob.sh] Running scripts...
2020/08/20 16:15:08 [cronjob.sh] Running Lazystream (NHL  via akc)...
error: The following required arguments were not provided:
    <FILE>

USAGE:
    lazystream generate xmltv <FILE> [--start-channel INT] [OPTIONS]

For more information try --help
2020/08/20 16:15:08 [cronjob.sh] Running Lazystream (MLB  via akc)...
error: The following required arguments were not provided:
    <FILE>

USAGE:
    lazystream generate xmltv <FILE> [--start-channel INT] [OPTIONS]

For more information try --help
2020/08/20 16:15:08 [cronjob.sh] Running guide2Go...
sed: /guide2go/"madtaz.yaml": No such file or directory
sed: /guide2go/"madtaz.yaml": No such file or directory
2020/08/20 16:15:08 [G2G  ] Version: 1.1.2
2020/08/20 16:15:08 [ERROR] open /guide2go/"madtaz.yaml: no such file or directory
2020/08/20 16:15:08 [cronjob.sh] Updating xTeVe...
2020/08/20 16:15:08 [cronjob.sh] {
2020/08/20 16:15:08 [cronjob.sh] "status": true
2020/08/20 16:15:08 [cronjob.sh] }{
2020/08/20 16:15:08 [cronjob.sh] "status": true
2020/08/20 16:15:08 [cronjob.sh] }{
2020/08/20 16:15:08 [cronjob.sh] "status": true

This is what my docker fill has

# Env
ENV PUID=1000 \
    PGID=1000 \
    XTEVE_PORT=${XTEVE_PORT} \
    use_xTeveAPI=yes \
    use_lazystream=yes \
    include_nhl=yes\
    include_mlb=yes \
    cdn=akc \ 
    use_guide2go=yes \
    YamlList="madtaz.yaml" \

**Comment by tarkah** [comment]
@taylorbourne This appears to be caused when `$args` is blank. I think that's passed to `lazystream` as the positional argument for the file name, which is blank, so it doesn't accept it.

**Comment by tarkah** [comment]
When cdn is set as not akc or a quality is specified, everything works. So its definitely the way we are trying to build the arguments with $args. I am not great with bash so I'm not 100% on what best practice is for building the arguments with it.

**Comment by MaDTaZ** [comment]
Fix with editing the .env. to look like this

### Lazystream Config
use_lazystream=yes
include_nhl=yes
include_mlb=yes
cdn=akc
**quality=720p60**

### Guide2go Config
use_guide2go=yes

## List of created lineup yaml files in /guide2go
# Exmaple with 3 lineups
and took out the "
YamlList=madtaz.yaml

**Comment by MaDTaZ** [comment]
Also look like it is just the mlb that is caring about the akc

2020/08/20 16:42:26 [cronjob.sh] Creating .m3u & .xml for XMLTV...
2020/08/20 16:42:26 [cronjob.sh] Playlist saved to: "/playlists/lazystream/lazystream-nhl.m3u"
2020/08/20 16:42:26 [cronjob.sh] Xmltv file saved to: "/playlists/lazystream/lazystream-nhl.xml"
**`2020/08/20 16:42:26 [cronjob.sh] Running Lazystream (MLB 720p60 via akc)...`**
2020/08/20 16:42:26 [cronjob.sh] Creating .m3u & .xml for XMLTV...
2020/08/20 16:42:26 [cronjob.sh] Playlist saved to: "/playlists/lazy

**Comment by tarkah** [comment]
Yeah, that's a workaround for now, setting the quality variable. We will get this fixed so it works out the box. Thanks for the bug report!

**Comment by taylorbourne** [comment]
Yeah that section is a bit wonky, we can probably clean it up. I'm a javascript developer so this will probably take some Googling.

**Comment by taylorbourne** [comment]
@tarkah I'm not going to lie, I don't even have this running locally so it's not like I'm testing all the things like I should be. I really need to figure out how to get this running outside of my unraid server.

**Comment by MaDTaZ** [comment]
Ya I was first making sure what was broken now i am looking into the crontab.sh I have not done programming for a bit

**Comment by taylorbourne** [comment]
So this is much cleaner.. basically stores args in an array. Though I don't think this fixes the blank space problem?

```
	params=()
	if [[ "$cdn" = "l3c" ]]; then
			params+=("--cdn l3c")
	fi
	if [[-z $quality]]; then
			params+=("--quality $quality")
	fi

	if [ "$include_nhl" = "yes" ]; then
		echo "Running Lazystream (NHL $quality via $cdn)..."
		mkdir -p /playlists/lazystream
		lazystream generate xmltv \
			--channel-prefix Lazystream:\ NHL \
			--start-channel 1000 "${params[@]}" \
			/playlists/lazystream/lazystream-nhl
	fi
	if [ "$include_mlb" = "yes" ]; then
		echo "Running Lazystream (MLB $quality via $cdn)..."
		mkdir -p /playlists/lazystream
		lazystream --sport mlb generate xmltv \
			--channel-prefix Lazystream:\ MLB \
			--start-channel 2000 "${params[@]}" \
			/playlists/lazystream/lazystream-mlb
	fi
fi```

**Comment by tarkah** [comment]
@taylorbourne you had the same idea as me with using an array :P review the PR I just submitted to fix this. I've tested with default ENV args and overriding quality and cdn

**Comment by MaDTaZ** [comment]
I am super new at docker when the fix comes out what is the best way fo updating. Right now I just make a back up of my xteve and then start overlol

**Comment by taylorbourne** [comment]
I guess it kind of depends on your setup.. I use Docker inside of an unraid server so it's extremely easy, updates are auto-detected and I click a button to apply. I know there's a way to do this with vanilla Docker as well, might take some Googlin.

**Comment by MaDTaZ** [comment]
so I am using linuxmint with docker so i will see what I can find on google.  Thanks again All
