### ISSUE TITLE
Video "issues"?

### ISSUE THREAD

**Issue by nexxai** [taylorbourne/xteve_lazystream#29]
I put "issues" in quotes here because I'm not sure that it's even an issue with this package, but I'm not really sure where else to ask.

When streaming an NHL game, I can see that it's getting the 720p stream and it starts playing, but the video doesn't "seem" like 60fps.  I know this is all a bit hand-wavy, so let me explain.

In the past, I've used LazyMan via Kodi and that was definitely clear as day, 60 fps.  It could easily pass as just another TV channel but on an HTPC or whatever; there was absolutely no motion jitter or any other artifacting.  However, using this package (and not saying it's the result of this package, just saying the problems only started when I started using it; it could very well be coincidental) it feels like there's some kind of transcoding or frame dropping somewhere along the chain which is really visible when the camera is panning quickly.  There's also some ghosting when a player is moving really quickly across the ice.

What I've checked so far:
- Plex is correctly showing that it's Direct Streaming:
```
Video - 720p (H.264) - Direct Stream
Audio - Unknown (AAC Stereo) - Direct Stream
```
- The ffmpeg flags being used within xTeVe include `-c copy` to ensure it's not transcoding

I know this is basically almost nothing to go on, but maybe someone has some advice?  I can't seem to find a way to get Plex to show the stream's FPS, but even if someone knows how to do that, that would be a great start.

**Comment by tarkah** [comment]
Yeah, so we actually added this as a variable you can specify to pass to lazystream.

In your .env file, specify:

```
quality=720p60
```

**Comment by nexxai** [comment]
@tarkah You are the man!  That was it exactly!  Thank you so much!
