### ISSUE TITLE
Web UI will not laod after a reboot

### ISSUE THREAD

**Issue by MaDTaZ** [taylorbourne/xteve_lazystream#30]
Hey All

I have been using this for a while but I dont reboot my computer very often last time I reboot I couldnt load the gui.   All I have to do to fix it is delete the .xteve folder then start the docker image back up and every thing is fine.  I then just restore my lastest backup.  I was wondering what you would need to troubleshoot or if you have an idea what it is doing wrong.  I have the newest image and running under linuxmint. I have the exact same setup on a different box and everything works with out and issue on the other box.  

Sorry forgot to mention I am running the docker image and it is the exact same image on the other computer

**Comment by tarkah** [comment]
I noticed this today as well. When I opened the xteve webpage from a private tab, it worked. So maybe some cookies or something were throwing things off?

Not 100% sure why this is happening, but glad you got it fixed!

**Comment by MaDTaZ** [comment]
> I noticed this today as well. When I opened the xteve webpage from a private tab, it worked. So maybe some cookies or something were throwing things off?
> 
> Not 100% sure why this is happening, but glad you got it fixed!

Good Call I didn't even think of cookies will have to try that on my next reboot.

**Comment by taylorbourne** [comment]
@MaDTaZ any updates here? This is an issue I haven't seen before. It might be worth checking out the xTeVe logs to see if there's anything useful there.

**Comment by MaDTaZ** [comment]
@taylorbourne So I actually was able to get it to do it even just stoping and starting the container.  I figured out I dont have to completely delete everything in the .xteve folder all I had to do was get rid of the .json files.  I will play with it again and see tomorrow.   I have alturismo/xteve installed as well to handle all my other iptv streams which doesn't do it.  where would the logs be stored I only have ever looked in the ui.

**Comment by taylor-verys** [comment]
I think the logs are actually displayed in the UI somewhere in the settings, let me know if you can’t find anything.

**Comment by MaDTaZ** [comment]
I was able to do more testing and I figured out what was happening I have 2 computers and one of image takes longer to start up so I wasn't waiting long enough.  I have both xteve image and this one loaded and the original one just boot quicker so I can refresh the page and it loads right away .  This one takes a few more moment to load. So chalk this up to being inpatient.
