### ISSUE TITLE
Games stop time bound to midnight

### ISSUE THREAD

**Issue by Foxcon84** [taylorbourne/xteve_lazystream#31]
If your on the east coast you end up with western games running past midnight. I noticed in the xmltv that the midnight seems to be the cutoff regardless of start time. In this case you'd end up with late starting games ending only after running an hour or so.

```
<programme channel="1022" start="20210114220000 -0400" stop="20210114235959 -0400">
<title lang="en">10:00 PM NATIONAL Canucks @ Oilers</title>

```

Would it be possible to just use a 3/4 hour limit instead of being bound to midnight?

**Comment by taylorbourne** [comment]
The XMLTV that this package generates is actually generated by LazyStream, probably better to open an issue there so @tarkah can track it accordingly. 

https://github.com/tarkah/lazystream

**Comment by tarkah** [comment]
@Foxcon84 I bumped lazystream w/ your PR and pushed that change to this master branch. Thanks again!

**Comment by Foxcon84** [comment]
@tarkah Awesome! Thanks for promoting this through 😁

**Comment by taylorbourne** [comment]
@Foxcon84 FYI this package has been bumped, latest should be available from DockerHub 👍
