### ISSUE TITLE
Unable to add to Plex - EPG issue?

### ISSUE THREAD

**Issue by kinghowdy** [taylorbourne/xteve_lazystream#36]
I believe there's an issue with the output of the EPG xml
I'm unable to add to Plex. It fails with "There was a problem saving your DVR. Please try again"
I added the m3u to telly and it will detect the channels. Adding the EPG causes it to fail.

> time="2021-02-13T19:39:43Z" level=info msg="telly is preparing to go live (version=1.1.0.6, branch=dev, revision=741108cd2100cf9f4d3a13f771d1ebe5132baae6)"
time="2021-02-13T19:39:43Z" level=info msg="Loading M3U from http://172.18.0.26:34400/m3u/xteve.m3u"
time="2021-02-13T19:39:43Z" level=info msg="Loading XMLTV from http://172.18.0.26::34400/xmltv/xteve.xml"
time="2021-02-13T19:39:43Z" level=error msg="Could not decode xmltv programme" error="the type Date field of date is not a time, value is: "
time="2021-02-13T19:39:43Z" level=error msg="error when parsing EPG" error="the type Date field of date is not a time, value is: "
time="2021-02-13T19:39:43Z" level=error msg="error when preparing provider" error="the type Date field of date is not a time, value is: "
time="2021-02-13T19:39:43Z" level=error msg="error when processing provider" error="the type Date field of date is not a time, value is: "
time="2021-02-13T19:39:43Z" level=info msg="telly is live and on the air!" 

Looking at the XML the date tag is blank  "<date/>"

I then added the device in Emby and signed up for Premiere and could see all the channels without an issue

I updated the date field in the XML and am still not able to add it to Plex.

**Comment by tarkah** [comment]
This is a known bug with xteve and plex

https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#plex-dvr-can-not-be-set-up-or-channels-are-missing

You need to access the xmltv file over file directory from plex, not from the URL

**Comment by kinghowdy** [comment]
Thanks for the reply. I moved the xteve.xml to a folder accessible from both xteve and Plex containers. I'm still getting the same error but I will attempt some further troubleshooting.

**Comment by kinghowdy** [comment]
Please mark this issue as closed. After further troubleshooting attempting to add the full EPG with NHL and MLB listings would not load in Plex. I decided to manually cut down the XML file. It loaded in Plex without an issue.
