### ISSUE TITLE
FFMPEG Streaming Stopped

### ISSUE THREAD

**Issue by tlsnine** [taylorbourne/xteve_lazystream#37]
Hi. I'm constantly receiving the following error when trying to view an NHL game:

> 2021/02/22 12:54:24 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204

I've verified my hosts are set correctly (x.x.201.101)
which ffmpeg shows /usr/bin/ffmpeg from within docker
Verified settings within xteve web itself
Pretty sure I have my .env file set correctly as the folders are populating

Same errors thrown regardless of OS (Mac Bigsur, Ubuntu 19.04 & 20.04) 

I saw a potential fix on tarkah's page regarding certs and such and performed those as well with no change.

Any assistance is appreciated as I know it's been a fantastic little app to have!

Thanks

**Comment by taylorbourne** [comment]
Hey @tlsnine sorry for the late reply – been busy lately. I always recommend to anyone who has issues with this package to attempt to run LazyStream on its own first and verify that you can watch streams there as you would expect. If you run into any problems open up an issue on the LazyStream repo. 

https://github.com/tarkah/lazystream

**Comment by taylorbourne** [comment]
Going to close this due to inactivity, but let me know if you need more help. Like I said, get lazystream working first. If that isn't working, the streams won't run in Plex either.
