### ISSUE TITLE
Question about updating

### ISSUE THREAD

**Issue by nexxai** [taylorbourne/xteve_lazystream#38]
We expect that there will probably be a new release of lazystream in the next day or two and so I'm wondering if there's a mechanism within this container to check for the latest release on startup and automatically update to it, or if it's something that has been considered.

**Comment by tarkah** [comment]
This is a great idea, as I need to push an update for this with the changes we just did.

We currently pull a specific release of lazystream when building the docker image. Theres 2 options here:

1. Have the dockerfile always pull the latest release. There's a couple downsides that come to mind for this.
2. Setup a github action from lazystream to directly commit to this repo and do a simple sed replace tag. For this I'd need some sort of secret key to commit to this repo from the other repos actions.

I like 2 better as it creates a new commit and therefore pushes an actual change to the dockerfile and `latest` will pull down that change.

**Comment by tarkah** [comment]
I'll look into this tomorrow

**Comment by nexxai** [comment]
I was actually thinking something more along the lines of how the linuxserver/docker-plex container updates itself: https://github.com/linuxserver/docker-plex/blob/master/root/etc/cont-init.d/60-plex-update

I don't think it needs to be nearly as complicated as that one is, but it basically just checks to see if there's a newer release than what it last saw, and then if so, grab a copy and extract it.

My concern(?) with having to pull down a new image is that the configuration goes away, does it not?  Or maybe I'm misunderstanding how containers work.

**Comment by tarkah** [comment]
Yeah that's a good idea... A runtime check on boot to check for a newer release. Therefore you don't need to pull down a newer image. I'll probably go with this route.

Pulling a new image isn't an issue as long as you're mounting the predefined volumes to somewhere on your filesystem. Then you can just use those same mount points with the new image

**Comment by nexxai** [comment]
Gotcha, but yeah, a check at runtime is awesome because then even if someone forgets to/doesn't update the image with the latest version number, the container will just go fetch it anyways.

**Comment by taylorbourne** [comment]
This is an awesome idea! Though for the record I check pretty frequently for LazyStream updates. Since my current set up “just works” I rarely need changes, but I’m always excited to keep that up to date.
