### ISSUE TITLE
MLB streams not working

### ISSUE THREAD

**Issue by shaksiwnl** [taylorbourne/xteve_lazystream#41]
Logs for when I click on an MLB stream: 

2021/03/18 20:54:25 [xTeVe] Streaming Status: Playlist: mlb - Tuner: 1 / 4
2021/03/18 20:54:25 [xTeVe] FFMPEG path: /usr/bin/ffmpeg
2021/03/18 20:54:25 [xTeVe] Streaming URL:
2021/03/18 20:54:25 [xTeVe] FFMPEG: Processing data
2021/03/18 20:54:25 [xTeVe] Streaming Status: Receive data from FFMPEG
2021/03/18 20:54:25 [xTeVe] FFMPEG log: : No such file or directory
**2021/03/18 20:54:25 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204**

Haven't used lazyman since they shut down last year. Is there any changes I need to make to my host machine? NHL streams are working fine.

**Comment by taylorbourne** [comment]
Should work fine without any changes! Do MLB streams work with the core app? I don't use those streams myself, I really only watch one hockey team – we just figured we may as welL support it all.

**Comment by taylorbourne** [comment]
Just saw this issue on laszystream as well

https://github.com/tarkah/lazystream/issues/71

I'm guessing MLB isn't working at all through LazyMan.

**Comment by shaksiwnl** [comment]
Thanks for the response! I'll post on the subreddit about it. Thanks :)

**Comment by taylorbourne** [comment]
Sounds good! I think I saw something about MLB on the subreddit as well. If you still have problems after LM is up and running at 100% feel free to open another issue. 👍
