### ISSUE TITLE
Remote Playlist and XMLTV not persisting upon restart

### ISSUE THREAD

**Issue by jwmoss** [taylorbourne/xteve_lazystream#42]
Hi all! I switched to this docker container after using [alturismo's docker container](https://github.com/alturismo/xteve_guide2go) for xTeVe and Guide2Go.

One big difference I noticed (besides the awesome integration with lazystream!) is that whenever I login to the UI within this version + create a new remote playlist + run guide2go to generate xmldv file, +  reboot the container, it does not persist any of my changes.

I'm assuming this is by design since this xTeVe container is largely driven by s6 docker overlay and .env files for docker. Is there any plans to address/add this in the future? Or am I completely missing something painfully obvious?

**Comment by taylorbourne** [comment]
Hey! So it sounds like maybe you're Docker volume isn't mounting correctly? Can you share how you're firing your container up?

**Comment by jwmoss** [comment]
> Hey! So it sounds like maybe you're Docker volume isn't mounting correctly? Can you share how you're firing your container up?

Thanks for the quick reply. Upon a second look, I had kept existing unRAID mounts and it appears had some issues re-creating the container and persisting in the folders that I had mapped , which is to say, I'm all set after re-creating from scratch!
