### ISSUE TITLE
How to update just lazystream in the Docker

### ISSUE THREAD

**Issue by schwyl** [taylorbourne/xteve_lazystream#45]
So lazystream in the docker is 4 revs behind now.

How can I just update it?

**Comment by tarkah** [comment]
The `latest` tag of the docker correctly pulls in the latest `1.11.4` release. Delete your container, update the image `latest` tag, and rebuild the container.

Make sure you volumes are mapped to your local filesystem so when you recreate the container, none of your changes (if any) get lost.

**Comment by tarkah** [comment]
This is where a docker-compose set up might be easier to manage things. See https://github.com/taylorbourne/xteve_lazystream/pull/44 for a start on that.

With docker compose, you can do `docker-compose down --rmi all` to remove the docker image. Then `docker-compose up -d` to recreate the container with a fresh image (it'll downloaded the latest).

**Comment by tarkah** [comment]
We may eventually add some logic to automatically update `lazystream` to the latest version at runtime, see suggestion here #38.

Once that's implemented, all you'd need to do is restart the container and it'd always make sure `lazystream` is up to date.

**Comment by schwyl** [comment]
Ah ok for some reason I thought i saw the docker image hadn't been updated for awhile

**Comment by taylorbourne** [comment]
@schwyl we are now checking for the latest version of LazyStream at runtime see #47 – this is in version `1.2.0`.. enjoy and let us know if you run into any issues!
