### ISSUE TITLE
Update dockerhub image

### ISSUE THREAD

**Issue by tarkah** [taylorbourne/xteve_lazystream#64]
@taylorbourne Can you publish a new release and update docker hub image? I just released [v1.11.8](https://github.com/tarkah/lazystream/releases/tag/v1.11.8) which includes the critical host name fix for resolving streams.

**Comment by MaDTaZ** [comment]
It also added --trim thank you very very much will test that out

**Comment by taylorbourne** [comment]
On it!

**Comment by taylorbourne** [comment]
Oh, you made it happen.. thanks @tarkah !
