### ISSUE TITLE
NHL not working through Plex

### ISSUE THREAD

**Issue by Riles554** [taylorbourne/xteve_lazystream#66]
I am getting a playback error "Could not tune channel. Please check your tuner or antenna." in Plex. Previously I had this error when the host file wasn't set correctly on my machine, but I am getting the same IP for the new hostname server and the hosts file appears to be working when I ping any of the three hostnames associated with the IP.

When attempting to use FFMpeg as streaming buffer I receive the following error:
[ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204.

Any thoughts since the new update? Removed the old file, updated and restarted docker and container - .m3u8 has today's games in it and if I individually test the links through VLC on a personal computer, they work fine. Just seems to be Plex having the issue.

Thanks!

**Comment by taylorbourne** [comment]
Assuming you've got the latest version of lazystream – try changing your buffer size to 1MB in the xTeVe settings.

**Comment by chippoman** [comment]
Does it play for a few minutes and then quit? Try changing buffer size to 1MB in xTeVe and transcoder buffer to 10000 seconds in Plex: https://forums.plex.tv/t/xteve-plex-this-live-tv-session-has-ended/752647/15

**Comment by taylorbourne** [comment]
@chippoman adjusting the buffer to 1MB fixed this problem for me last week, thanks for posting the link with the extra information there maybe I'll add this to my setup as well. 👍

**Comment by taylorbourne** [comment]
@chippoman @Riles554 so I took a look at the fix there – I would recommend changing the xTeVe buffer to 1MB and testing that out first before changing the Plex transcoder buffer. You might see some adverse performance (or if your short on space storage issues) issues once you go down that route.

Nice to see everyone chipping in to help out, these setups can be super frustrating.

**Comment by Riles554** [comment]
@taylorbourne @chippoman thanks for both of your help! This is a fantastic piece of software. 

I was able to get it back running, it seems like lazystream was not cooperating even though I had installed the latest release. After a full uninstall and reinstall everything seems to be smooth again. I changed to the 1MB buffer and all seems to be smooth as butter.

Running all of this off a VPS with 1 core and 2gb of ram, absolutely amazing how well it works even with next to no resources.

**Comment by goldenpipes** [comment]
i've done everything listed above and im getting the same error. 

```2021/11/02 21:30:22 [xTeVe] [ERROR] FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204```

even tried a fresh VM with a fresh docker install and i get the same issue.

**Comment by chesh1r3k** [comment]
All streams are having an issue today. It may all be shutdown. Everyone is waiting for developers to see if this is the end.

**Comment by taylorbourne** [comment]
Anyone subbed to this thread – latest realize makes the host configurable.. so just make sure to set the `lazyStreamHost` environment variable as you see fit.

While we resolved the initial problems by altering the xTeVe config, the latter issues are resolved by #72
