### ISSUE TITLE
Error updating lazystream to 1.11.8

### ISSUE THREAD

**Issue by chippoman** [taylorbourne/xteve_lazystream#67]
I was having issues today with the .m3u being blank (no URLs). After investigating, it might be due to lazystream's update to 1.11.8 and this docker's update-lazystream.sh having issues downloading it from github:

[update-lazystream] checking for update
[update-lazystream] installed version: v1.11.6

[update-lazystream] remote version: v1.11.8

[update-lazystream] newer version available, downloading...

Are you sure you want to trust it? (y/N): Connecting to github.com (140.82.112.4:443)
wget: server returned error: HTTP/1.1 404 Not Found

tar: can't open 'lazystream.tar.gz': No such file or directory
mv: cannot stat '././lazystream': No such file or directory
rm: cannot remove 'lazystream.tar.gz': No such file or directory
[update-lazystream] lazystream successfully updated to v1.11.8

**Comment by tarkah** [comment]
We've updated the docker image, so just update that instead and you should be good to go!

**Comment by chippoman** [comment]
All good. Issue on my end actually. My env didn't have $lazyStreamReleaseName set which resulted in the 404 when grabbing the latest release from github.
