### ISSUE TITLE
Cannot stream using DockerHub image + Emby

### ISSUE THREAD

**Issue by xWulfie** [taylorbourne/xteve_lazystream#71]
Greetings!
I have been using and loving your addon for Plex/Emby. I know things have been pretty interesting in this space recently, but even after StevensNJD ceased his project, yours was still working for me as of Sun/Mon. Tuesday evening it would not work for me even after installing the newest update from DockerHub. 

I use the Dockerhub version because I use Unraid and it is the simplest thing to use for me (who does not code much at all). 

Currently receiving this error in Emby; even after updating XML guide list:
Playback Error
No compatible streams are currently available. Please try again later or contact your system administrator for details.

**Comment by chesh1r3k** [comment]
All streams are having issues tonight. See the issue at the bottom of the issues list for this project. Something may have changed, or it may all be down for good. The developers are looking into it.

**Comment by xWulfie** [comment]
> All streams are having issues tonight. See the issue at the bottom of the issues list for this project. Something may have changed, or it may all be down for good. The developers are looking into it.

I'm definitely aware of the 'stuff' that is going on. However, I know there are other 'hosts' that can be used. Unless they are all coming down as well.

**Comment by chesh1r3k** [comment]
The "mouse" is involved now with the lawsuit. Don't be surprised if it all comes down. You can apparently ping freegames.ddns.net and update your hosts file, but who knows if this will be a consistent fix. I'm waiting for updates like everyone else while watching 3 different projects to see what the fix will be.

**Comment by taylorbourne** [comment]
@xWulfie @chesh1r3k latest version I just published `1.4` makes the host configurable – if you update make sure you have the `lazyStreamHost` environment variable set

**Comment by taylorbourne** [comment]
resolved by #72

**Comment by taylorbourne** [comment]
2

**Comment by chesh1r3k** [comment]
Where do you get the new host from for the variable?

**Comment by xWulfie** [comment]
I'm also a bit confused on how to set the new host. Since I am using a docker container via Unraid, would my setup be different? I have tried looking for the .env file but could not find it to edit.

**Comment by taylorbourne** [comment]
> I'm also a bit confused on how to set the new host. Since I am using a docker container via Unraid, would my setup be different? I have tried looking for the .env file but could not find it to edit.
> 
> 

Just go to the docker page and right click the icon for this container and click edit. I think at the bottom of the screen there's a button you can use to add new variables. 

When the window pops up make sure you change the config type drop down to variable. The key should be `lazyStreamHost` and the value should be your updated host name. Please check Reddit for the host name `r/nhl_games` is a good place to watch.
