### ISSUE TITLE
Channels won't stay enabled on Plex

### ISSUE THREAD

**Issue by strenkml** [taylorbourne/xteve_lazystream#76]
If I add the tuner to Plex the sports channels show in the guide.  But when I check back later the channels are disabled.  I can add them back but I have to manual match the channel to the channel from the guide.  It is much easier to just remove the tuner and re-add it.

**Comment by tarkah** [comment]
Which version of the docker image are you using?

Make sure to have the latest image, and ensure in your .env file, you have `trim_xmltv=no`

**Comment by taylorbourne** [comment]
Possibly related to the refresh process being wonky – I'll cut a release tomorrow.

Though would be interested in what version you're running. Are you seeing "unknown airing" in your guide before you go to remap?

**Comment by taylorbourne** [comment]
@strenkml Please try `1.5.1`

**Comment by chesh1r3k** [comment]
So, this is weird, nothing changed except updated to 1.5.1.  Plex is now updating the guide fine, but now Jellyfin is loading all the channels, but there's no guide information on them. Can't even tune them. 
![Screenshot_20211201-180028](https://user-images.githubusercontent.com/26318809/144338691-3e74fd99-e3ba-4546-baf8-405dde917c61.png)
Jellyfin hasn't had a new update for 2mo. Tried restarting it and forcing a guide refresh all with the same outcome.

**Comment by taylorbourne** [comment]
@chesh1r3k thanks for posting.. man this update thing is annoying. Try restarting the container, then refresh in plex. Someday we’ll get this working without user input…

**Comment by chesh1r3k** [comment]
The latest thing I notice is that the container takes about 6min to finish starting up. It gets to here, right after starting and then hands for 4-5mins before moving on:

`2021/12/01 18:06:05 [cronjob.sh] Playlist saved to: "/playlists/lazystream/lazystream-nhl.m3u"
2021/12/01 18:06:05 [cronjob.sh] Xmltv file saved to: "/playlists/lazystream/lazystream-nhl.xml"
+ set +x
2021/12/01 18:06:05 [cronjob.sh] Running Lazystream (MLB via l3c)...
+ lazystream generate xmltv --cdn l3c --sport mlb --channel-prefix 'Lazystream: MLB' --start-channel 2000 /playlists/lazystream/lazystream-mlb
2021/12/01 18:06:05 [cronjob.sh] Creating .m3u & .xml for XMLTV...

ERROR: No games for today.

+ set +x
2021/12/01 18:06:05 [cronjob.sh] Updating xTeVe...'

Not sure why it started doing that. But, I did restart the container and refreshed Plex and it seems to still be loading the only game left tonight. I'll try again tomorrow before any new games are on.

**Comment by strenkml** [comment]
> @strenkml Please try `1.5.1`

Sorry. Its been a busy couple of days.  I just downloaded it and will let you know if I have the same issue.

**Comment by strenkml** [comment]
> Which version of the docker image are you using?
> 
> Make sure to have the latest image, and ensure in your .env file, you have `trim_xmltv=no`

I already have that set to no.

**Comment by goldenpipes** [comment]
> trim_xmltv=no
where do i set that? im using unraid do i just add a new variable named trim_xmltv ? with a value of no?

maybe im having a different issue today, lazystream is saying there are no streams today.

**Comment by taylorbourne** [comment]
I keep getting no games as well – my solutions is to restart the container, restart Plex, and refresh guide. I really want to get this figured out so all the info you guys post helps. 

The hang described above is to be expected, there's an intentional 30 second sleep after we update xTeVe to give it a chance to do its thing. Something else seems to be breaking with the games though?

🤨

**Comment by chesh1r3k** [comment]
Mine was showing no games as well in both Jellyfin and Plex when I went to watch the Avs tonight. Restarted the container and refreshed my guides and all was good. Set a cron job to restart xteve_lazystream every day at 6am. I'll look and see if I have a populated guide tomorrow, or if it loses the schedule before games come on in the afternoon.

**Comment by chesh1r3k** [comment]
> > trim_xmltv=no
> > where do i set that? im using unraid do i just add a new variable named trim_xmltv ? with a value of no?
> 
> maybe im having a different issue today, lazystream is saying there are no streams today.

Yes, create a variable in the container called trim_xmltv and set it's value to no. That's how you create all the environment variables for this container in unRAID. You can look at the sample.env file for all of the variables that are available.

**Comment by strenkml** [comment]
1.5.1 has the same issue.  I tried restarting the container and then manually refreshing the guide, but the channels are just disabled in Plex.
![Screenshot 2021-12-02 232921](https://user-images.githubusercontent.com/25540117/144545378-f4e2d7e4-5490-4212-9a5d-c371d997a2c1.png)

The 10 enabled channels are from dizquetv.

Let me know if you want any other information.

**Comment by taylorbourne** [comment]
@strenkml how are you adding the guide data to Plex? Are you using the URL from xTeVe or a direct path to the xml file? If you're using the former I would try the latter. 

I haven't seen this happen yet so not too sure. Maybe post up some logs from xTeVe so we can see if there are any clues there?

**Comment by tarkah** [comment]
> @strenkml how are you adding the guide data to Plex? Are you using the URL from xTeVe or a direct path to the xml file? If you're using the former I would try the latter.

Definitely this. I haven't had guide issues, but I mount the `.xteve` folder to my Plex container and point to the xml file directly. See the issue specifically here: https://github.com/xteve-project/xTeVe-Documentation/blob/master/en/troubleshooting.md#plex-dvr-can-not-be-set-up-or-channels-are-missing

**Comment by strenkml** [comment]
> @strenkml how are you adding the guide data to Plex? Are you using the URL from xTeVe or a direct path to the xml file? If you're using the former I would try the latter.
> 
> I haven't seen this happen yet so not too sure. Maybe post up some logs from xTeVe so we can see if there are any clues there?

Yeah I was using the URL. I just switched it to the file path.
Hopefully that fixes it

**Comment by strenkml** [comment]
Nope the channels disabled themselves again.  The interesting thing is that the dizquetv channels are also being supplied by xteve but for some reason they dont get disabled.

**Comment by strenkml** [comment]
I just found this issue for Dizquetv: https://github.com/vexorian/dizquetv/issues/396

I'm going to guess this is my issue. I'm going to try removing the dizquetv channels and see if that fixes it.

**Comment by taylorbourne** [comment]
Very nice, if I get some time tonight I'll close this issue out and open a new one for the issue that's causing us to have to restart the container for games to load.

**Comment by strenkml** [comment]
Yep that fixed it

**Comment by goldenpipes** [comment]
im still having to restart the container everyday.  i seen there was an update so ill check it again tomorrow.

**Comment by taylorbourne** [comment]
@goldenpipes yep, please try the latest release.. I'm happy to report that today (first day with latest changes from master) I did not have to do any jumping through hoops. Tonight's schedule has loaded without any issues, and my guide as a whole is looking good.
