### ISSUE TITLE
Feature Request: Make default channel number configurable

### ISSUE THREAD

**Issue by JoshNotWright** [taylorbourne/xteve_lazystream#80]
MLB starts at 2000 forcing it's channels to the end of the guide in my setup each time, but NHL starts at 1000. Because of this, if I want to add a new dizquetv channel, I have to remap xteve otherwise it will be added after all the NHL channels.

**Comment by taylorbourne** [comment]
This issue would make more sense over in the LazyStream repo, as LS is responsible for generating the m3u and xmltv guide data.

https://github.com/tarkah/lazystream

**Comment by tarkah** [comment]
This is already an option in Lazystream!

`--start-channel <number>` can be passed to change the starting channel number (defaults to 1000).

**Comment by taylorbourne** [comment]
@tarkah ah duh, I knew that lmao.. thanks! Sorry little scatter brained, my daughter was born 12/29 and everything is a blur since.

**Comment by tarkah** [comment]
No worries, I often forget what capabilities it has at this point as well :P

Congratulations!! Hope you're getting lots of relaxation time in with her.

**Comment by MaDTaZ** [comment]
> This is already an option in Lazystream!
> 
> `--start-channel <number>` can be passed to change the starting channel number (defaults to 1000).
> 
> Edit: Here's where we pass it for both NHL & MLB, we can change these to source from the `.env` file:
> 
> https://github.com/taylorbourne/xteve_lazystream/blob/a64b617c24cc79ed1640c080f87df6b0f455ec95/root/cronjob.sh#L32-L33
> 
> https://github.com/taylorbourne/xteve_lazystream/blob/a64b617c24cc79ed1640c080f87df6b0f455ec95/root/cronjob.sh#L56-L57

Hey I was just wonder how I get this to stick everytime it update I have to put it back?

 nhl_args+=("--exclude-feeds" "COMPOSITE" "FRENCH")     
                nhl_args+=("--channel-prefix")                         
                nhl_args+=("--trim")                                            
                nhl_args+=("Lazystream: NHL")                                   
                nhl_args+=("--start-channel")                       
                nhl_args+=("1")

**Comment by tarkah** [comment]
@MaDTaZ We've merged #81 so you can configure this in the .env file.  See the updated https://github.com/taylorbourne/xteve_lazystream/blob/master/sample.env which includes these new variables.

> I use a compose file do I need to use .env in that to keep it there. example of my file

Yes, use a `.env` file in the same folder as your `docker-compose.yml` and it should work.

**Comment by MaDTaZ** [comment]
> @MaDTaZ We've merged #81 so you can configure this in the .env file. See the updated https://github.com/taylorbourne/xteve_lazystream/blob/master/sample.env which includes these new variables.
> 
> > I use a compose file do I need to use .env in that to keep it there. example of my file
> 
> Yes, use a `.env` file in the same folder as your `docker-compose.yml` and it should work.

thanks
