### ISSUE TITLE
FFMPEG error

### ISSUE THREAD

**Issue by neauxm** [taylorbourne/xteve_lazystream#85]
Installed in UnRaid, it was working initially, went back to it an hour later and now I cannot play. Here is the error from the log.

FFMPEG error (Streaming was stopped by third party transcoder (FFmpeg / VLC)) - EC: 1204

**Comment by taylorbourne** [comment]
Unfortunately that error message could mean a ton of different things. Are you able to play the stream in VLC? If you can, we can rule out the possibility that the stream you selected just isn't working. 

Did you spot check a few streams just to be sure?

**Comment by neauxm** [comment]
I checked a number of streams last night. Initially after I setup it last night, everything was working, showed all the games in the guide and the 3 streams I tried worked. I came back to it about an hour later and none of the streams work. 

Today, it’s reporting either Unknown stream in plex ( on my phone) and on my Apple TV, it’s reporting Lazystream: NHL 1 and so on.

**Comment by neauxm** [comment]
Also, if I paste the M3u url into the network stream spot on VLC it loads NHL stream 1 and plays the Buffalo address. 

Copying this link from the top of the Xteve WeBGui: http://IP:port/m3u/xteve.m3u

**Comment by neauxm** [comment]
I re-added Xteve to plex, and used a link to the xml instead of the url. Same issue. Unknown Airing. If I click any of the channels it still only plays the Buffalo streams from yesterday 

![image](https://user-images.githubusercontent.com/76253418/161166976-b1d06614-d71e-4bbb-9b35-b71bd6888174.jpeg)
